{
 "title": "Lotus Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job:",
    "query": {
     "query": "label_values(lotus_miner_info,job)"
    }
   },
   {
    "name": "miner_id",
    "label": "Miner ID",
    "query": {
     "query": "label_values(lotus_miner_info{job=\"$job\"},miner_id)"
    }
   },
   {
    "name": "worker_addr",
    "label": "Worker Address",
    "query": {
     "query": "label_values(lotus_miner_info{miner_id=\"$miner_id\"},worker_addr)"
    }
   },
   {
    "name": "owner_addr",
    "label": "Owner Address",
    "query": {
     "query": "label_values(lotus_miner_info{miner_id=\"$miner_id\"},owner_addr)"
    }
   },
   {
    "name": "control0_addr",
    "label": "Control Address 0",
    "query": {
     "query": "label_values(lotus_miner_info{miner_id=\"$miner_id\"},control0_addr)"
    }
   },
   {
    "name": "worker_host",
    "label": "Worker",
    "query": {
     "query": "query_result(sort(lotus_miner_worker_cpu{miner_id=\"$miner_id\"}))"
    }
   },
   {
    "name": "storage_id",
    "label": "Storage",
    "query": {
     "query": "label_values(lotus_miner_storage_info{miner_id=\"$miner_id\"},storage_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Network QAP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_network_qap{instance=\"10.200.2.21:9100\",miner=\"f01896422\"}",
     "legendFormat": "Network QAP"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "nfarad" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_chain_basefee{instance=\"10.200.2.10:9100\",node=\"NodeCluster\"}",
     "legendFormat": "Basefee"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "msgs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_mpool_pending{instance=\"10.200.2.10:9100\",node=\"Node01\"}",
     "legendFormat": "Mpool pending"
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Node01",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lotus_block_age{node=\"Node01\"}",
     "legendFormat": "Node01"
    }
   ]
  },
  {
   "title": "Node Height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_chain_height{instance=\"10.200.2.10:9100\",node=\"Node01\"}",
     "legendFormat": "Height"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lotus_block_age{instance=\"10.200.2.10:9100\",node=\"Node01\"}",
     "legendFormat": "Block Age"
    }
   ]
  },
  {
   "title": "Free Disk Space",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_disk_free_space{instance=\"10.200.2.10:9100\",node=\"Node01\"}",
     "legendFormat": "Disk Free Space"
    }
   ]
  },
  {
   "title": "Node02",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lotus_block_age{instance=\"10.200.2.11:9100\",node=\"Node02\"}",
     "legendFormat": "Node02"
    }
   ]
  },
  {
   "title": "Node Height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_chain_height{instance=\"10.200.2.11:9100\",node=\"Node02\"}",
     "legendFormat": "Height"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_block_age{instance=\"10.200.2.11:9100\",node=\"Node02\"}",
     "legendFormat": "Block Age"
    }
   ]
  },
  {
   "title": "Free Disk Space",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_disk_free_space{instance=\"10.200.2.11:9100\",node=\"Node02\"}",
     "legendFormat": "Disk Free Space"
    }
   ]
  },
  {
   "title": "Local Pending",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "msgs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_mpool_pending_local{instance=\"10.200.2.10:9100\",node=\"Node01\"}",
     "legendFormat": "Local pending"
    }
   ]
  },
  {
   "title": "Net Peers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_net_peers{instance=\"10.200.2.10:9100\",node=\"Node01\"}",
     "legendFormat": "Netpeers"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_block_validation{instance=\"10.200.2.10:9100\",node=\"Node01\"}",
     "legendFormat": "Block Validation"
    }
   ]
  },
  {
   "title": "Local Pending",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "msgs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lotus_mpool_pending_local{instance=\"10.200.2.11:9100\",node=\"Node02\"}",
     "legendFormat": "Local pending"
    }
   ]
  },
  {
   "title": "Net Peers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_net_peers{instance=\"10.200.2.11:9100\",node=\"Node02\"}",
     "legendFormat": "Netpeers"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lotus_block_validation{instance=\"10.200.2.11:9100\",node=\"Node02\"}",
     "legendFormat": "Block Validation"
    }
   ]
  },
  { "title": "Mining Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Total Mining Power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(lotus_miner_qap{miner=\"f02055660\"}))+(sum(lotus_miner_qap{miner=\"f01896422\"}))+(sum(lotus_miner_qap{miner=\"f0773157\"}))+(sum(lotus_miner_qap{miner=\"f02172481\"}))",
     "legendFormat": "Total QAP"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(lotus_miner_qap{miner=\"f01896422\"})+sum(lotus_miner_qap{miner=\"f02055660\"})+sum(lotus_miner_qap{miner=\"f02172481\"}))/sum(lotus_network_qap{miner=\"f01896422\"})",
     "legendFormat": "Pwr rate"
    },
    {
     "expr": "1/((sum(lotus_miner_qap{miner=\"f01896422\"})+sum(lotus_miner_qap{miner=\"f02055660\"})+sum(lotus_miner_qap{miner=\"f02172481\"}))/sum(lotus_network_qap{miner=\"f01896422\"})*2*5/60)",
     "legendFormat": "Block every"
    },
    {
     "expr": "(sum(lotus_miner_qap{miner=\"f01896422\"})+sum(lotus_miner_qap{miner=\"f02055660\"})+sum(lotus_miner_qap{miner=\"f02172481\"}))/sum(lotus_network_qap{miner=\"f01896422\"})*5*60*2*24",
     "legendFormat": "Mining rate"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(lotus_miner_faulty_sectors{miner=\"f02055660\"}) + sum(lotus_miner_faulty_sectors{miner=\"f01896422\"}) + sum(lotus_miner_faulty_sectors{miner=\"f0773157\"}) + sum(lotus_miner_faulty_sectors{miner=\"f02172481\"})",
     "legendFormat": "Faults"
    }
   ]
  },
  { "title": "f02055660", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "QAP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lotus_miner_qap{miner=\"f02055660\"}",
     "legendFormat": "QAP"
    }
   ]
  },
  {
   "title": "RBP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lotus_miner_active_sectors{miner=\"f02055660\"}*32*1024*1024*1024",
     "legendFormat": "QAP"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lotus_miner_qap{miner=\"f02055660\"}/lotus_network_qap{miner=\"f02055660\"}",
     "legendFormat": "Pwr rate"
    },
    {
     "expr": "1/(lotus_miner_qap{miner=\"f02055660\"}/lotus_network_qap{miner=\"f02055660\"}*2*5/60)",
     "legendFormat": "Block every"
    },
    {
     "expr": "lotus_miner_qap{miner=\"f02055660\"}/lotus_network_qap{miner=\"f02055660\"}*5*60*2*24",
     "legendFormat": "Mining rate"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_miner_eligible{miner=\"f02055660\"}",
     "legendFormat": "Mining"
    },
    {
     "expr": "lotus_miner_proving_window{miner=\"f02055660\"}",
     "legendFormat": "WdPost"
    }
   ]
  },
  {
   "title": "Base",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_miner_base_delta{miner=\"f02055660\"}",
     "legendFormat": "Base Delta"
    }
   ]
  },
  {
   "title": "Sectors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_miner_active_sectors{miner=\"f02055660\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "lotus_miner_faulty_sectors{miner=\"f02055660\"}",
     "legendFormat": "Faulty"
    },
    {
     "expr": "lotus_miner_sector_status_removed{miner=\"f02055660\"}",
     "legendFormat": "Removed"
    }
   ]
  },
  {
   "title": "Sealing Workers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lotus_miner_sealing_ap_worker{miner=\"f02055660\"}",
     "legendFormat": "AP"
    },
    {
     "expr": "lotus_miner_sealing_pc1_worker{miner=\"f02055660\"}",
     "legendFormat": "PC1"
    },
    {
     "expr": "lotus_miner_sealing_pc2_worker{miner=\"f02055660\"}",
     "legendFormat": "PC2"
    },
    {
     "expr": "lotus_miner_sealing_c2_worker{miner=\"f02055660\"}",
     "legendFormat": "C2"
    }
   ]
  },
  {
   "title": "Sealing Pipeline",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_miner_sector_status{miner=\"f02055660\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Store",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_miner_store_used{miner=\"f02055660\"}",
     "legendFormat": "Store Used"
    },
    {
     "expr": "lotus_miner_store_space{miner=\"f02055660\"}",
     "legendFormat": "Store"
    }
   ]
  },
  {
   "title": "Seal",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_miner_seal_used{miner=\"f02055660\"}",
     "legendFormat": "Store Used"
    },
    {
     "expr": "lotus_miner_seal_space{miner=\"f02055660\"}",
     "legendFormat": "Store"
    }
   ]
  },
  {
   "title": "Available Balances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "FIL" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_miner_balances{miner=\"f02055660\",wallet=\"miner_available\"}",
     "legendFormat": "Miner"
    },
    {
     "expr": "lotus_miner_wallet_balances{miner=\"f02055660\",wallet=\"owner_balance\"}",
     "legendFormat": "Owner"
    },
    {
     "expr": "lotus_miner_wallet_balances{miner=\"f02055660\",wallet=\"worker_balance\"}",
     "legendFormat": "Worker"
    },
    {
     "expr": "lotus_miner_wallet_balances{miner=\"f02055660\",wallet=\"control0_balance\"}",
     "legendFormat": "Control0"
    },
    {
     "expr": "lotus_miner_balances{miner=\"f02055660\",wallet=\"market_available\"}",
     "legendFormat": "Market"
    }
   ]
  },
  {
   "title": "Locked Balances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 11, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "FIL" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_miner_balances{miner=\"f02055660\",wallet=\"precommit\"}",
     "legendFormat": "PreCommit"
    },
    {
     "expr": "lotus_miner_balances{miner=\"f02055660\",wallet=\"pledge\"}",
     "legendFormat": "Pledge"
    },
    {
     "expr": "lotus_miner_balances{miner=\"f02055660\",wallet=\"vesting\"}",
     "legendFormat": "Vesting"
    },
    {
     "expr": "lotus_miner_balances{miner=\"f02055660\",wallet=\"market_locked\"}",
     "legendFormat": "Market"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 7, "x": 17, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_miner_sector_error{miner=\"f02055660\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "f01896422", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "QAP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lotus_miner_qap{miner=\"f01896422\"}",
     "legendFormat": "QAP"
    }
   ]
  },
  {
   "title": "RBP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lotus_miner_active_sectors{miner=\"f01896422\"}*32*1024*1024*1024",
     "legendFormat": "QAP"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lotus_miner_qap{miner=\"f01896422\"}/lotus_network_qap{miner=\"f01896422\"}",
     "legendFormat": "Pwr rate"
    },
    {
     "expr": "1/(lotus_miner_qap{miner=\"f01896422\"}/lotus_network_qap{miner=\"f01896422\"}*2*5/60)",
     "legendFormat": "Block every"
    },
    {
     "expr": "lotus_miner_qap{miner=\"f01896422\"}/lotus_network_qap{miner=\"f01896422\"}*5*60*2*24",
     "legendFormat": "Mining rate"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_miner_eligible{miner=\"f01896422\"}",
     "legendFormat": "Mining"
    },
    {
     "expr": "lotus_miner_proving_window{miner=\"f01896422\"}",
     "legendFormat": "WdPost"
    }
   ]
  },
  {
   "title": "Base",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_miner_base_delta{miner=\"f01896422\"}",
     "legendFormat": "Base Delta"
    }
   ]
  },
  {
   "title": "Sectors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_miner_active_sectors{miner=\"f01896422\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "lotus_miner_faulty_sectors{miner=\"f01896422\"}",
     "legendFormat": "Faulty"
    },
    {
     "expr": "lotus_miner_sector_status_removed{miner=\"f01896422\"}",
     "legendFormat": "Removed"
    }
   ]
  },
  {
   "title": "Sealing Workers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lotus_miner_sealing_ap_worker{miner=\"f01896422\"}",
     "legendFormat": "AP"
    },
    {
     "expr": "lotus_miner_sealing_pc1_worker{miner=\"f01896422\"}",
     "legendFormat": "PC1"
    },
    {
     "expr": "lotus_miner_sealing_pc2_worker{miner=\"f01896422\"}",
     "legendFormat": "PC2"
    },
    {
     "expr": "lotus_miner_sealing_c2_worker{miner=\"f01896422\"}",
     "legendFormat": "C2"
    }
   ]
  },
  {
   "title": "Sealing Pipeline",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_miner_sector_status{miner=\"f01896422\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Store",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_miner_store_used{miner=\"f01896422\"}",
     "legendFormat": "Store Used"
    },
    {
     "expr": "lotus_miner_store_space{miner=\"f01896422\"}",
     "legendFormat": "Store"
    }
   ]
  },
  {
   "title": "Seal",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_miner_seal_used{miner=\"f01896422\"}",
     "legendFormat": "Store Used"
    },
    {
     "expr": "lotus_miner_seal_space{miner=\"f01896422\"}",
     "legendFormat": "Store"
    }
   ]
  },
  {
   "title": "Available Balances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "FIL" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_miner_balances{miner=\"f01896422\",wallet=\"miner_available\"}",
     "legendFormat": "Miner"
    },
    {
     "expr": "lotus_miner_wallet_balances{miner=\"f01896422\",wallet=\"owner_balance\"}",
     "legendFormat": "Owner"
    },
    {
     "expr": "lotus_miner_wallet_balances{miner=\"f01896422\",wallet=\"worker_balance\"}",
     "legendFormat": "Worker"
    },
    {
     "expr": "lotus_miner_wallet_balances{miner=\"f01896422\",wallet=\"control0_balance\"}",
     "legendFormat": "Control0"
    },
    {
     "expr": "lotus_miner_balances{miner=\"f01896422\",wallet=\"market_available\"}",
     "legendFormat": "Market"
    }
   ]
  },
  {
   "title": "Locked Balances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 11, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "FIL" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_miner_balances{miner=\"f01896422\",wallet=\"precommit\"}",
     "legendFormat": "PreCommit"
    },
    {
     "expr": "lotus_miner_balances{miner=\"f01896422\",wallet=\"pledge\"}",
     "legendFormat": "Pledge"
    },
    {
     "expr": "lotus_miner_balances{miner=\"f01896422\",wallet=\"vesting\"}",
     "legendFormat": "Vesting"
    },
    {
     "expr": "lotus_miner_balances{miner=\"f01896422\",wallet=\"market_locked\"}",
     "legendFormat": "Market"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 7, "x": 17, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_miner_sector_error{miner=\"f01896422\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Free Disk Space",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lotus_miner_data_disks{miner=\"f01896422\",label=\"data01\"}"
    },
    {
     "expr": "lotus_miner_data_disks{miner=\"f01896422\",label=\"data05\"}"
    },
    {
     "expr": "lotus_miner_data_disks{miner=\"f01896422\",label=\"data06\"}"
    },
    {
     "expr": "lotus_miner_data_disks{miner=\"f01896422\",label=\"data07\"}"
    }
   ]
  },
  {
   "title": "Free Disk Space",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"10.200.1.21:9100\",device=\"/dev/sdd\"}"
    }
   ]
  },
  { "title": "f02172481", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "QAP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lotus_miner_qap{miner=\"f02172481\"}",
     "legendFormat": "QAP"
    }
   ]
  },
  {
   "title": "RBP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lotus_miner_active_sectors{miner=\"f02172481\"}*32*1024*1024*1024",
     "legendFormat": "QAP"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lotus_miner_qap{miner=\"f02172481\"}/lotus_network_qap{miner=\"f02172481\"}",
     "legendFormat": "Pwr rate"
    },
    {
     "expr": "1/(lotus_miner_qap{miner=\"f02172481\"}/lotus_network_qap{miner=\"f02172481\"}*2*5/60)",
     "legendFormat": "Block every"
    },
    {
     "expr": "lotus_miner_qap{miner=\"f02172481\"}/lotus_network_qap{miner=\"f02172481\"}*5*60*2*24",
     "legendFormat": "Mining rate"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_miner_eligible{miner=\"f02172481\"}",
     "legendFormat": "Mining"
    },
    {
     "expr": "lotus_miner_proving_window{miner=\"f02172481\"}",
     "legendFormat": "WdPost"
    }
   ]
  },
  {
   "title": "Base",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_miner_base_delta{miner=\"f02172481\"}",
     "legendFormat": "Base Delta"
    }
   ]
  },
  {
   "title": "Sectors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_miner_active_sectors{miner=\"f02172481\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "lotus_miner_faulty_sectors{miner=\"f02172481\"}",
     "legendFormat": "Faulty"
    },
    {
     "expr": "lotus_miner_sector_status_removed{miner=\"f02172481\"}",
     "legendFormat": "Removed"
    }
   ]
  },
  {
   "title": "Sealing Workers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lotus_miner_sealing_ap_worker{miner=\"f02172481\"}",
     "legendFormat": "AP"
    },
    {
     "expr": "lotus_miner_sealing_pc1_worker{miner=\"f02172481\"}",
     "legendFormat": "PC1"
    },
    {
     "expr": "lotus_miner_sealing_pc2_worker{miner=\"f02172481\"}",
     "legendFormat": "PC2"
    },
    {
     "expr": "lotus_miner_sealing_c2_worker{miner=\"f02172481\"}",
     "legendFormat": "C2"
    }
   ]
  },
  {
   "title": "Sealing Pipeline",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_miner_sector_status{miner=\"f02172481\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Store",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_miner_store_used{miner=\"f02172481\"}",
     "legendFormat": "Store Used"
    },
    {
     "expr": "lotus_miner_store_space{miner=\"f02172481\"}",
     "legendFormat": "Store"
    }
   ]
  },
  {
   "title": "Seal",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_miner_seal_used{miner=\"f0773157\"}",
     "legendFormat": "Store Used"
    },
    {
     "expr": "lotus_miner_seal_space{miner=\"f0773157\"}",
     "legendFormat": "Store"
    }
   ]
  },
  {
   "title": "Available Balances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 4, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "FIL" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_miner_balances{miner=\"f02172481\",wallet=\"miner_available\"}",
     "legendFormat": "Miner"
    },
    {
     "expr": "lotus_miner_wallet_balances{miner=\"f02172481\",wallet=\"owner_balance\"}",
     "legendFormat": "Owner"
    },
    {
     "expr": "lotus_miner_wallet_balances{miner=\"f02172481\",wallet=\"worker_balance\"}",
     "legendFormat": "Worker"
    },
    {
     "expr": "lotus_miner_wallet_balances{miner=\"f02172841\",wallet=\"control0_balance\"}",
     "legendFormat": "Control0"
    },
    {
     "expr": "lotus_miner_balances{miner=\"f02172481\",wallet=\"market_available\"}",
     "legendFormat": "Market"
    }
   ]
  },
  {
   "title": "Locked Balances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 11, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "FIL" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_miner_balances{miner=\"f02172481\",wallet=\"precommit\"}",
     "legendFormat": "PreCommit"
    },
    {
     "expr": "lotus_miner_balances{miner=\"f02172481\",wallet=\"pledge\"}",
     "legendFormat": "Pledge"
    },
    {
     "expr": "lotus_miner_balances{miner=\"f02172481\",wallet=\"vesting\"}",
     "legendFormat": "Vesting"
    },
    {
     "expr": "lotus_miner_balances{miner=\"f02172481\",wallet=\"market_locked\"}",
     "legendFormat": "Market"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 7, "x": 17, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_miner_sector_error{miner=\"f02172481\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "f0773157", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "QAP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lotus_miner_qap{miner=\"f0773157\"}",
     "legendFormat": "QAP"
    }
   ]
  },
  {
   "title": "RBP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lotus_miner_active_sectors{miner=\"f0773157\"}*32*1024*1024*1024",
     "legendFormat": "QAP"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lotus_miner_qap{miner=\"f0773157\"}/lotus_network_qap{miner=\"f0773157\"}",
     "legendFormat": "Pwr rate"
    },
    {
     "expr": "1/(lotus_miner_qap{miner=\"f0773157\"}/lotus_network_qap{miner=\"f0773157\"}*2*5/60)",
     "legendFormat": "Block every"
    },
    {
     "expr": "lotus_miner_qap{miner=\"f0773157\"}/lotus_network_qap{miner=\"f0773157\"}*5*60*2*24",
     "legendFormat": "Mining rate"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_miner_eligible{miner=\"f0773157\"}",
     "legendFormat": "Mining"
    },
    {
     "expr": "lotus_miner_proving_window{miner=\"f0773157\"}",
     "legendFormat": "WdPost"
    }
   ]
  },
  {
   "title": "Base",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_miner_base_delta{miner=\"f0773157\"}",
     "legendFormat": "Base Delta"
    }
   ]
  },
  {
   "title": "Sectors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_miner_active_sectors{miner=\"f0773157\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "lotus_miner_faulty_sectors{miner=\"f0773157\"}",
     "legendFormat": "Faulty"
    },
    {
     "expr": "lotus_miner_sector_status_removed{miner=\"f0773157\"}",
     "legendFormat": "Removed"
    }
   ]
  },
  {
   "title": "Sealing Workers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lotus_miner_sealing_ap_worker{miner=\"f0773157\"}",
     "legendFormat": "AP"
    },
    {
     "expr": "lotus_miner_sealing_pc1_worker{miner=\"f0773157\"}",
     "legendFormat": "PC1"
    },
    {
     "expr": "lotus_miner_sealing_pc2_worker{miner=\"f0773157\"}",
     "legendFormat": "PC2"
    },
    {
     "expr": "lotus_miner_sealing_c2_worker{miner=\"f0773157\"}",
     "legendFormat": "C2"
    }
   ]
  },
  {
   "title": "Sealing Pipeline",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_miner_sector_status{miner=\"f0773157\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Store",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_miner_store_used{miner=\"f0773157\"}",
     "legendFormat": "Store Used"
    },
    {
     "expr": "lotus_miner_store_space{miner=\"f0773157\"}",
     "legendFormat": "Store"
    }
   ]
  },
  {
   "title": "Seal",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_miner_seal_used{miner=\"f02172481\"}",
     "legendFormat": "Store Used"
    },
    {
     "expr": "lotus_miner_seal_space{miner=\"f02172481\"}",
     "legendFormat": "Store"
    }
   ]
  },
  {
   "title": "Available Balances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 4, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "FIL" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_miner_balances{miner=\"f0773157\",wallet=\"miner_available\"}",
     "legendFormat": "Miner"
    },
    {
     "expr": "lotus_miner_wallet_balances{miner=\"f0773157\",wallet=\"owner_balance\"}",
     "legendFormat": "Owner"
    },
    {
     "expr": "lotus_miner_wallet_balances{miner=\"f0773157\",wallet=\"worker_balance\"}",
     "legendFormat": "Worker"
    },
    {
     "expr": "lotus_miner_wallet_balances{miner=\"f0773157\",wallet=\"control0_balance\"}",
     "legendFormat": "Control0"
    },
    {
     "expr": "lotus_miner_market_available_balance{miner=\"f0773157\"}",
     "legendFormat": "Market"
    }
   ]
  },
  {
   "title": "Locked Balances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 11, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "FIL" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_miner_balances{miner=\"f0773157\",wallet=\"precommit\"}",
     "legendFormat": "PreCommit"
    },
    {
     "expr": "lotus_miner_balances{miner=\"f0773157\",wallet=\"pledge\"}",
     "legendFormat": "Pledge"
    },
    {
     "expr": "lotus_miner_balances{miner=\"f0773157\",wallet=\"vesting\"}",
     "legendFormat": "Vesting"
    },
    {
     "expr": "lotus_miner_balances{miner=\"f0773157\",wallet=\"market_locked\"}",
     "legendFormat": "Market"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 7, "x": 17, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_miner_sector_error{miner=\"f0773157\"}",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}